### ISSUE TITLE
New node-inspector doesn't work in IIS 7.5?

### ISSUE THREAD

**Issue by dpolivy** [tjanczuk/iisnode#372]
I see that node-inspector has been updated in the latest versions of iisnode – do you know if it will work in IIS 7.5, or does it require 8 due to the WebSockets usage?

I can’t seem to get it to work for me (just get a blank grey bar at the top of the page, and an "error" Event in the console), so just wanted to make sure it was even possible to run it on 7.5 before spending more effort troubleshooting.

**Comment by dpolivy** [comment]
I've since updated to Windows 10, and am trying to get this to work. I can get the node-inspector UI to load, but I get this error when I try to click on the Sources tab (and nothing happens):

`Uncaught TypeError: WebInspector.CallStackSidebarPane is not a function`

It does look like the websockets connection is successfully upgraded:

```
Request URL:ws://localhost/m/server.js/debug/ws
Request Method:GET
Status Code:101 Switching Protocols
Response Headers
view source
Connection:Upgrade
Date:Wed, 05 Aug 2015 21:20:24 GMT
Sec-WebSocket-Accept:mgLcmOTYaW5caVQb8+7pcQTNp6g=
Server:Microsoft-IIS/10.0
Upgrade:websocket
Request Headers
view source
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:Upgrade
DNT:1
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
Sec-WebSocket-Key:+IF3lvWfVUGdZGkB6g251w==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36
```

Any ideas?

**Comment by dpolivy** [comment]
@rramachand21 I'm still having trouble getting the new node inspector to work on Win10. Should this work with node v0.10? I have WebSockets disabled in the web.config, but the WebSockets handshake to the node inspector isn't establishing; it's returning 500 instead.

**Comment by rramachand21** [comment]
@dpolivy v0.2.21 has the fix for new node-inspector integration - have you tried this version of iisnode?

**Comment by dpolivy** [comment]
@rramachand21 I just installed the new version and it does get further than before. I see the UI, and everything loads (including the websocket connection), but I get this error in the console:

````
ScriptsPanel.js:132 Uncaught TypeError: WebInspector.CallStackSidebarPane is not a constructor
````

Have you seen that before?

**Comment by rramachand21** [comment]
I have not seen this before - are you able to debug with the new version?

**Comment by dpolivy** [comment]
No, it does not work, presumably because the script panel doesn't load. Is there a minimum version of nodejs required for this to work?

**Comment by rramachand21** [comment]
I have tried with 4.4.3 and it works - let me know if it works with this version in your case too?

**Comment by dpolivy** [comment]
I'm not sure what changed, but now it seems to be working with Node v0.10.42. Maybe it needed a reboot.
